# Generated by Django 5.1.6 on 2025-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Scheduled', max_length=50)),
            ],
        ),
    ]
